asns:
- 57724,262254
debug: true
email: d.shmidt@ddos-guard.net
irr: radb
logstash:
  enable: true
  host: 10.11.2.78
  port: 1514
main_asn:
- '57724'
min_hosts: 3
slack:
  enable: false
  url: null
telegram:
  chat_id: null
  enable: false
  token: null
uplinks:
  IPTP: '41095'
  NTT: '2914'
  Nls_kz: '200590'
  RT: '12389'
  Smartnet_kz: '43994'
  TTK: '20485'
  Telia: '1299'
